Repository UnBArqDsw2023-2/2023.2_G5_ProjetoAmericanas, pull requests merged in 2023-12, with the labels that each got.

#94 Corrige diagrama estados e adicionado fluxo de produtos
  docs/Modelagem/2.1.2.3.DiagramaDeEstados.md
  docs/img/diagramadeestados_atualizado.png
  docs/img/fluxo_produtos.drawio.png
Labels: documentation

#115 Implementado padrão Observer
  backend/americanas/models/Produto.py
  backend/americanas/views/ProdutoView.py
  backend/observer/BaseObserver.py
  backend/observer/ProdutoObserver.py
  backend/observer/__init__.py
Labels: enhancement

#113 Implementado padrão Strategy para buscar métricas das notas das Avaliações
  backend/americanas/models/Avaliacao.py
  backend/americanas/serializers/AvaliacaoSerializer.py
  backend/americanas/services/AvaliacaoService.py
  backend/americanas/views/AvaliacaoView.py
  backend/americanas/views/__init__.py
  backend/core/urls.py
  backend/strategy/__init__.py
  backend/strategy/base_strategy.py
Labels: enhancement

#116 Corrige implementacao Strategy
  backend/Dockerfile
  backend/americanas/models/Avaliacao.py
  backend/americanas/models/Contem.py
  backend/americanas/models/Endereco.py
  backend/americanas/models/EnderecoUsuario.py
  backend/americanas/models/Pedido.py
  backend/americanas/models/Produto.py
  backend/americanas/models/Usuario.py
  backend/strategy/base_strategy.py
  backend/template_method/__init__.py
  backend/template_method/base_model.py
Labels: bug

#120 Docs/estruturar_wiki
  docs/ArquiteturaReutilizacao/4.1.PadroesArquiteturais.md
  docs/ArquiteturaReutilizacao/4.2.ReutilizacaoDeSoftware.md
  docs/ArquiteturaReutilizacao/4.ArquiteturaReutilizacao.md
Labels: documentation

#118 Das visao logica
  docs/ArquiteturaReutilizacao/4.1.1.DAS.md
Labels: documentation

#123 Implementar strategy carteira pagamentos
  backend/americanas/strategy/__init__.py
  backend/americanas/strategy/strategy.py
  backend/americanas/views/AvaliacaoView.py
  backend/americanas/views/PedidoView.py
  backend/americanas/views/__init__.py
  backend/core/urls.py
  backend/strategy2/__init__.py
  backend/strategy2/base_strategy.py
  docs/ArquiteturaReutilizacao/4.2.1.Strategy.md
  docs/img/requisicao_meio_pagamento.png
Labels: documentation, enhancement

#124 docs: atualiza Home
  docs/README.md
Labels: documentation

#127 Adicionado parte de processos e introdução
  docs/ArquiteturaReutilizacao/4.1.1.DAS.md
  docs/img/img_logical_develop.png
Labels: documentation
